ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS subscription_status character varying(32);
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS ai_enabled boolean;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS automation_enabled boolean;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS broadcast_enabled boolean;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS daily_message_limit integer;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS monthly_ai_tokens bigint;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS projection_version integer;
ALTER TABLE whatsapp_account_capabilities ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS status character varying(50);
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS quality_rating character varying(20);
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS is_verified boolean;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS last_webhook_received timestamp without time zone;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS last_outbound_sent timestamp without time zone;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS last_error_message text;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS last_error_code integer;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_account_status ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS waba_id character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS phone_number_id character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS display_phone_number character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS verified_name character varying(255);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS custom_name character varying(128);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS quality_score character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS messaging_limit integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS access_token_encrypted text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS token_type character varying(16);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS token_expires_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS connected_by_user_id character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_synced_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS flow_private_key text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS flow_public_key text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS notification_phone_number character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS is_coexistence boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS mps_limit integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS meta_business_id character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS sync_status character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_echo_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS coexistence_paired_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS history_sync_completed boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS safe_mode_reason_code character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS safe_mode_override_expires_at timestamp with time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_cooldown_ends_at timestamp with time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS operational_metrics jsonb;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS notification_email character varying(255);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS ai_enabled boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS ai_model character varying(50);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS temperature double precision;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS max_tokens integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS prompt_override text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS knowledge_base_id character varying(100);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS connection_status character varying(50);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS is_verified boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_webhook_received timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_outbound_sent timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_error_message text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_error_code integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS onboarding_lifecycle_state character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS warmup_started_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS warmup_ends_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS warmup_config jsonb;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS operational_mode character varying(24);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS safe_mode_advisory_only boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS safe_mode_reason text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS restriction_state character varying(40);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS restriction_reason text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS restriction_detected_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS restriction_source character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_subscription_status character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_success_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_failure_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_error text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_health character varying(24);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_checked_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_subscribed_app_verified boolean;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS last_inbound_webhook_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_echo_validation jsonb;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_validated_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_last_event_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_failure_reason text;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS webhook_failure_count integer;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS token_health character varying(24);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS token_health_checked_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS token_health_detail jsonb;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS embedded_signup_version character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS graph_version_used character varying(16);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS fb_sdk_version character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS whatsapp_config_id_used character varying(64);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS message_health_metrics jsonb;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS trust_score numeric(6,2);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS trust_score_computed_at timestamp without time zone;
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS ownership_model_version character varying(32);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS customer_webhook_url character varying(512);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS customer_webhook_secret_header character varying(128);
ALTER TABLE whatsapp_accounts ADD COLUMN IF NOT EXISTS customer_webhook_secret_value character varying(512);
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS rule_id integer;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS conversation_id integer;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS trigger_message_id integer;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS trigger_text text;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS matched_keyword character varying(255);
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS response_message_id integer;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS response_success boolean;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS response_error text;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_automation_logs ADD COLUMN IF NOT EXISTS response_time_ms integer;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS automation_id integer;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS node_id character varying(64);
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS node_type character varying(32);
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS position_x double precision;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS position_y double precision;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS data json;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS execution_order integer;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_automation_nodes ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS rule_type character varying(32);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS status character varying(32);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS trigger_config json;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS response_type character varying(32);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS response_config json;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS cooldown_seconds integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS max_triggers_per_day integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS trigger_count integer;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS last_triggered_at timestamp without time zone;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS created_by character varying(255);
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_automation_rules ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS ai_enabled boolean;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS ai_model character varying(50);
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS temperature double precision;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS max_tokens integer;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS prompt_override text;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS knowledge_base_id character varying(100);
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_bot_settings ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS timezone character varying(64);
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS schedule json;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS is_enabled boolean;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_business_hours ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS conversation_id integer;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS phone_number character varying(32);
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS automation_id integer;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS current_node_id character varying(64);
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS last_button_clicked character varying(64);
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS state_data json;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS last_user_message_at timestamp without time zone;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS is_within_24h_window boolean;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_conversation_states ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS user_phone character varying(32);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS user_name character varying(255);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS status character varying(16);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS unread_count integer;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS last_inbound_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS last_outbound_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS session_expires_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS closed_by_agent boolean;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS closed_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS entry_source character varying(32);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS ctwa_clid character varying(255);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS ad_id character varying(64);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS campaign_id character varying(64);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS adset_id character varying(64);
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS attribution_data json;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS attributed_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS last_message_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_conversations ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS access_token_encrypted text;
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS phone_number_id character varying(64);
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS waba_id character varying(64);
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_credentials ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_dataset_rows ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_dataset_rows ADD COLUMN IF NOT EXISTS dataset_id integer;
ALTER TABLE whatsapp_dataset_rows ADD COLUMN IF NOT EXISTS data json;
ALTER TABLE whatsapp_dataset_rows ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_dataset_rows ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS columns json;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS column_mapping json;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS source_type character varying(50);
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS source_config json;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS last_sync_at timestamp with time zone;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS sync_status character varying(20);
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS sync_error text;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS total_rows integer;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_datasets ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS trigger_type character varying(50);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS trigger_value character varying(255);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS sheet_id text;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS sheet_name character varying(255);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS phone_column character varying(100);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS column_mapping json;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS fallback_values json;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS last_synced_row integer;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS enrolled_count integer;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS completed_count integer;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_drip_campaigns ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS campaign_id integer;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS phone_number character varying(50);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS phone_original character varying(100);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS current_step_order integer;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS next_run_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS status character varying(20);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS status_reason text;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS variables json;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS variables_source character varying(32);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS variables_row_index integer;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS variables_sheet_id character varying(255);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS variables_last_synced_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS last_sent_params json;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS tracking_id character varying(64);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS clicked boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS click_count integer;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS clicked_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS message_id character varying(128);
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS sent boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS delivered boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS read boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS failed boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS replied boolean;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS delivered_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
ALTER TABLE whatsapp_drip_enrollments ADD COLUMN IF NOT EXISTS replied_at timestamp with time zone;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS campaign_id integer;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS step_order integer;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS delay_seconds integer;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS template_name character varying(255);
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS language character varying(10);
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_drip_steps ADD COLUMN IF NOT EXISTS scheduled_at timestamp with time zone;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS workspace_id character varying(36);
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS question text;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS answer text;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS keywords jsonb;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS category character varying(64);
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS match_type character varying(32);
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS match_threshold double precision;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS priority integer;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS match_count integer;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS last_matched_at timestamp with time zone;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_faqs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS workspace_id integer;
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS media_id character varying(128);
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS mime_type character varying(64);
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS sha256 character varying(128);
ALTER TABLE whatsapp_favorite_stickers ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS name character varying(128);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS category character varying(32);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS flow_version integer;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS parent_flow_id integer;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS flow_json json;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS schema_version character varying(16);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS entry_screen_id character varying(64);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS meta_flow_id character varying(64);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS status character varying(16);
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_flows ADD COLUMN IF NOT EXISTS published_at timestamp without time zone;
ALTER TABLE whatsapp_form_blocked_dates ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_form_blocked_dates ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_form_blocked_dates ADD COLUMN IF NOT EXISTS blocked_date character varying(10);
ALTER TABLE whatsapp_form_blocked_dates ADD COLUMN IF NOT EXISTS reason character varying(255);
ALTER TABLE whatsapp_form_blocked_dates ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS flow_id integer;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS conversation_id integer;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS wa_id character varying(32);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS customer_name character varying(128);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS booking_date character varying(10);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS booking_time character varying(8);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS service_type character varying(128);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS status character varying(16);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS remind_at timestamp without time zone;
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS reminder_job_id character varying(64);
ALTER TABLE whatsapp_form_bookings ADD COLUMN IF NOT EXISTS reminded boolean;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS day_of_week integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS day_name character varying(16);
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS open_time character varying(8);
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS close_time character varying(8);
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS slot_duration_minutes integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS max_bookings_per_slot integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS max_bookings_per_day integer;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_form_business_hours ADD COLUMN IF NOT EXISTS timezone character varying(64);
ALTER TABLE whatsapp_jobs ADD COLUMN IF NOT EXISTS id character varying(191);
ALTER TABLE whatsapp_jobs ADD COLUMN IF NOT EXISTS next_run_time double precision;
ALTER TABLE whatsapp_jobs ADD COLUMN IF NOT EXISTS job_state bytea;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS workspace_id integer;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS intent_rules jsonb;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS confidence_threshold double precision;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS auto_discovery_enabled boolean;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS notify_enabled boolean;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS notify_template character varying(255);
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS notify_destinations jsonb;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS nurture_enabled boolean;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_lead_growth_settings ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS source character varying(64);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS source_type character varying(64);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS tracking_id character varying(64);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS phone_number character varying(32);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS template_name character varying(255);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS campaign_name character varying(255);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS target_url text;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS wamid character varying(128);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS utm_source character varying(128);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS utm_campaign character varying(255);
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS click_count integer;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS first_clicked_at timestamp with time zone;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS last_clicked_at timestamp with time zone;
ALTER TABLE whatsapp_link_tracking ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS wamid character varying(128);
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS status character varying(16);
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS "timestamp" timestamp without time zone;
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS error_code character varying(16);
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS raw_event json;
ALTER TABLE whatsapp_message_status_events ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS conversation_id integer;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS direction character varying(16);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS type character varying(32);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS template_name character varying(128);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS template_category character varying(32);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS campaign_id integer;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS content json;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS wamid character varying(128);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS status character varying(16);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS error_code character varying(16);
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS sent_at timestamp without time zone;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS delivered_at timestamp without time zone;
ALTER TABLE whatsapp_messages ADD COLUMN IF NOT EXISTS read_at timestamp without time zone;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS event_type character varying(64);
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS previous_mode character varying(64);
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS new_mode character varying(64);
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS context jsonb;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone;
ALTER TABLE whatsapp_operational_logs ADD COLUMN IF NOT EXISTS actor character varying(64);
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS phone_number_id character varying(64);
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS captured_at timestamp without time zone;
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS quality_rating character varying(16);
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS messaging_tier character varying(32);
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS name_status character varying(64);
ALTER TABLE whatsapp_phone_reputation_snapshots ADD COLUMN IF NOT EXISTS raw_graph jsonb;
ALTER TABLE whatsapp_send_idempotency ADD COLUMN IF NOT EXISTS dedup_key character varying(255);
ALTER TABLE whatsapp_send_idempotency ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS meta_template_id character varying(64);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS name character varying(512);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS category character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS language character varying(16);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS status character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS local_status character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS meta_status character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS is_archived boolean;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS archived_at timestamp without time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS rejection_reason text;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS quality_score character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS components json;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS body_text text;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS header_text character varying(512);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS footer_text character varying(256);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS variable_count integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS confidence_initial integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS confidence_post_submit integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS submitted_at timestamp without time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS approved_at timestamp without time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS approval_duration_seconds integer;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS approval_outcome_reason character varying(64);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS validation_flags json;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS detected_intent character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS approval_path character varying(32);
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_templates ADD COLUMN IF NOT EXISTS last_synced_at timestamp without time zone;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS phone character varying(32);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS email character varying(255);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS custom_fields text;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS tags text;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS list_name character varying(255);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS opted_out boolean;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS opted_out_at timestamp with time zone;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS source character varying(64);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS external_id character varying(255);
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_trigger_contacts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS trigger_id integer;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS recipient_phone character varying(32);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS variables_json text;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS source_ip character varying(64);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS source_type character varying(32);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS source_reference character varying(255);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS success boolean;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS message_id character varying(128);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS delivery_status character varying(32);
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS delivered_at timestamp with time zone;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
ALTER TABLE whatsapp_trigger_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS slug character varying(255);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS template_name character varying(255);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS language character varying(10);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS secret_key character varying(64);
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS allow_custom_variables boolean;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS trigger_count integer;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS last_triggered_at timestamp with time zone;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
ALTER TABLE whatsapp_triggers ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS id bigint;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS event_type character varying(64);
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS event_key character varying(191);
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS message_id integer;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS wamid character varying(128);
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS occurred_at timestamp without time zone;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS payload json;
ALTER TABLE whatsapp_usage_events ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS workspace_id character varying(255);
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS account_id integer;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS name character varying(255);
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS trigger_type character varying(32);
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS trigger_config json;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS nodes json;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS edges json;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS viewport json;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS status character varying(32);
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS trigger_count integer;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS last_triggered_at timestamp without time zone;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS version integer;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS created_by character varying(255);
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS variables json;
ALTER TABLE whatsapp_visual_automations ADD COLUMN IF NOT EXISTS flow_config json;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS id integer;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS raw_json text;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS event_type character varying(64);
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS phone_number_id character varying(64);
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS processed boolean;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS received_at timestamp without time zone;
ALTER TABLE whatsapp_webhook_logs ADD COLUMN IF NOT EXISTS processed_at timestamp without time zone;
